# Generated by Django 5.2.7 on 2025-11-03 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Unique slug for stable reuse across sections/pages",
                        max_length=150,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name for editors", max_length=150
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("cta", "CTA"),
                            ("link", "Link"),
                            ("html", "Raw HTML"),
                            ("json", "JSON Data"),
                        ],
                        max_length=20,
                    ),
                ),
                ("text", models.TextField(blank=True)),
                (
                    "json",
                    models.JSONField(
                        blank=True,
                        help_text="Structured content (title, subtitle, cta, etc.)",
                        null=True,
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="items/")),
                ("file", models.FileField(blank=True, null=True, upload_to="items/")),
                ("url", models.URLField(blank=True)),
                (
                    "reusable",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this item can be reused in multiple sections",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Additional extensible data for the item",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PageType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("landing", "Landing Page"),
                            ("sales", "Sales Page"),
                            ("product", "Product Page"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "section_definitions",
                    models.JSONField(
                        blank=True,
                        help_text='JSON like {"hero": {"items": ["text1", "text2", "video", "cta"]}, "benefits": {"items": ["item1", "item2", ..., "item6"]}}',
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ModularLandingPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "page_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of page (defines sections and item slots)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pages.pagetype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "section_code",
                    models.CharField(
                        help_text="Section code (hero, benefits, cta)", max_length=50
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("override_text", models.TextField(blank=True)),
                ("override_json", models.JSONField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="pages.item",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_items",
                        to="pages.modularlandingpage",
                    ),
                ),
            ],
            options={
                "ordering": ["section_code", "order"],
                "abstract": False,
            },
        ),
    ]
