# Generated by Django 5.2.7 on 2025-11-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_page_type_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='Specific data for the section in JSON format'),
        ),
    ]
