# Generated by Django 5.2.7 on 2025-11-05 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_section_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='content',
        ),
    ]
