# Generated by Django 5.1.12 on 2025-11-01 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Campaña')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('template', models.CharField(default='webinar.html', max_length=100, verbose_name='Template')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('cta_button_text', models.CharField(default='Registrarme', max_length=100, verbose_name='Texto del Botón CTA')),
                ('whatsapp_number', models.CharField(default='1234567890', max_length=20, verbose_name='Número de WhatsApp')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Vistas')),
                ('conversion_count', models.PositiveIntegerField(default=0, verbose_name='Conversiones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landings.campaign', verbose_name='Campaña')),
            ],
            options={
                'verbose_name': 'Página de Landing',
                'verbose_name_plural': 'Páginas de Landing',
                'ordering': ['-created_at'],
            },
        ),
    ]
